title: Задачи
href: index.md
items:
  - name: О задачах в Битрикс24
    href: index.md
  - name: Структура связей объектов задач
    href: structure-connections.md
  - name: Поля задачи
    href: fields.md
  - name: Добавление задачи
    href: tasks-task-add.md
  - name: Изменение задачи
    href: tasks-task-update.md
  - name: Получение задачи по идентификатору
    href: tasks-task-get.md
  - name: Получение списка задач
    href: tasks-task-list.md
  - name: Прикрепление файлов к задаче
    href: tasks-task-files-attach.md
  - name: Принятие задачи
    href: tasks-task-approve.md
  - name: Перевод задачи в статус «завершена»
    href: tasks-task-complete.md
  - name: Получение счетчиков пользователя
    href: tasks-task-counters-get.md
  - name: Перевод задачи в статус «отложена»
    href: tasks-task-defer.md
  - name: Делегирование задачи
    href: tasks-task-delegate.md
  - name: Удаление задачи
    href: tasks-task-delete.md
  - name: Отклонение задачи
    href: tasks-task-disapprove.md
  - name: Добавление задачи в Избранное
    href: tasks-task-favorite-add.md
  - name: Удаление задачи из Избранного
    href: tasks-task-favorite-remove.md
  - name: Получение списка полей
    href: tasks-task-get-fields.md
  - name: Проверка доступа к задаче
    href: tasks-task-get-access.md
  - name: История задачи
    href: tasks-task-history-list.md
  - name: Перевод задачи в статус «ждет выполнения»
    href: tasks-task-pause.md
  - name: Возобновление задачи после ее завершения
    href: tasks-task-renew.md
  - name: Перевод задачи в статус «выполняется»
    href: tasks-task-start.md
  - name: Включение наблюдения за задачей
    href: tasks-task-start-watch.md
  - name: Отключение наблюдения за задачей
    href: tasks-task-stop-watch.md
  - name: Включение режима «Без звука»
    href: tasks-task-mute.md
  - name: Отключение режима «Без звука»
    href: tasks-task-unmute.md
  - name: Создать связь между задачами
    href: task-dependence-add.md
  - name: Удалить связь между задачами
    href: task-dependence-delete.md
  - name: Результат задачи
    include:
      path: result/toc.yaml
      mode: link
  - name: События
    include:
      path: events-tasks/toc.yaml
      mode: link
  - name: Чек-листы
    include:
      path: checklist-item/toc.yaml
      mode: link
  - name: Комментарии
    include:
      path: comment-item/toc.yaml
      mode: link
  - name: Затраченное время
    include:
      path: elapsed-item/b24-toc.yaml
      mode: link
  - name: Пользовательские поля
    include:
      path: user-field/toc.yaml
      mode: link
  - name: Мой план
    include:
      path: stages/toc.yaml
      mode: link
  - name: План рабочего дня
    include:
      path: planner/toc.yaml
      mode: link
  - name: Устаревшее
    include:
      path: deprecated/b24-toc.yaml
      mode: link